# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-5eb67045-4c12-4eea-8089-1f6ccca1a865";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5eb67045-4c12-4eea-8089-1f6ccca1a865".device = "/dev/disk/by-uuid/5eb67045-4c12-4eea-8089-1f6ccca1a865";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FC8C-997F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-93e3cbb3-68d1-4cf3-a246-eeffc642c9e1"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
